<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="DESKTOP-7769JJ2" name="org.rerun.Test1" tests="11" failures="1" timestamp="05 Nov 2021 12:21:51 GMT" time="0.047" errors="0">
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.016" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.016" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.rerun.Test1.tc1(Test1.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.015" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.000" classname="org.rerun.Test1">
    <skipped/>
  </testcase> <!-- tc1 -->
</testsuite> <!-- org.rerun.Test1 -->
